# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='body',
        ),
    ]
